apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep1
  labels:
    sub: scheduling
    type: exercise
spec:
  containers:
   - name: busybox
     image: busybox
     command:
       - sleep
       - "100"
