apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep2
  labels:
    sub: scheduling
    type: exercise
spec:
  nodeSelector:
    name: node3
  containers:
   - name: busybox
     image: busybox
     command:
       - sleep
       - "100"
